services:
  runner1:
    build: .
    container_name: github-runner-expense-bot-1
    restart: always
    environment:
      REPO_URL: '${REPO_URL}'
      ACCESS_TOKEN: '${ACCESS_TOKEN}'
      RUNNER_NAME: expense-bot-runner1
      RUNNER_WORKDIR: /tmp/github-runner-expense-bot
      LABELS: 'playground-ubuntu,self-hosted'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'runner1-work:/tmp/github-runner-expense-bot'
  runner2:
    build: .
    container_name: github-runner-expense-bot-2
    restart: always
    environment:
      REPO_URL: '${REPO_URL}'
      ACCESS_TOKEN: '${ACCESS_TOKEN}'
      RUNNER_NAME: expense-bot-runner2
      RUNNER_WORKDIR: /tmp/github-runner-expense-bot
      LABELS: 'playground-ubuntu,self-hosted'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'runner2-work:/tmp/github-runner-expense-bot'
  runner3:
    build: .
    container_name: github-runner-expense-bot-3
    restart: always
    environment:
      REPO_URL: '${REPO_URL}'
      ACCESS_TOKEN: '${ACCESS_TOKEN}'
      RUNNER_NAME: expense-bot-runner3
      RUNNER_WORKDIR: /tmp/github-runner-expense-bot
      LABELS: 'playground-ubuntu,self-hosted'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'runner3-work:/tmp/github-runner-expense-bot'

  runner4:
    build: .
    container_name: github-runner-expense-bot-4
    restart: always
    environment:
      REPO_URL: '${REPO_URL}'
      ACCESS_TOKEN: '${ACCESS_TOKEN}'
      RUNNER_NAME: expense-bot-runner4
      RUNNER_WORKDIR: /tmp/github-runner-expense-bot
      LABELS: 'playground-ubuntu,self-hosted'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'runner4-work:/tmp/github-runner-expense-bot'

volumes:
  runner1-work: null
  runner2-work: null
  runner3-work: null
  runner4-work: null
