on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 20 19 * * *
name: Semgrep
permissions:
  contents: read

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: [self-hosted, Linux, X64, playground-ubuntu]
    permissions:
      contents: read
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
      with:
        egress-policy: audit

    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      with:
        persist-credentials: false

    - name: Run semgrep
      run: semgrep ci --exclude-rule package_managers.renovate.renovate-missing-minimum-release-age.renovate-missing-minimum-release-age

  otel-cicd-action:
    if: always()
    name: OpenTelemetry Export Trace
    runs-on: [self-hosted, Linux, X64, playground-ubuntu]
    permissions:
      contents: read
      actions: read
    needs: [semgrep]
    steps:
    - name: Export workflow
      uses: corentinmusard/otel-cicd-action@895874bfae14f840e3032f1a14c3f2b45c93f4af # v4
      with:
        otlpEndpoint: ${{ vars.OTEL_EXPORTER_OTLP_ENDPOINT }}/v1/traces
        otlpHeaders: ${{ secrets.OTEL_EXPORTER_HEADERS }}
        githubToken: ${{ secrets.GITHUB_TOKEN }}
