name: GitHub Actions Security Analysis with zizmor 🌈

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["**"]

permissions: {}

jobs:
  zizmor:
    name: Run zizmor 🌈
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # Required for upload-sarif (used by zizmor-action) to upload SARIF files.
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false

      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@5f14fd08f7cf1cb1609c1e344975f152c7ee938d # v0.5.6

  otel-cicd-action:
    if: always()
    name: OpenTelemetry Export Trace
    runs-on: [self-hosted, Linux, X64, playground-ubuntu]
    permissions:
      contents: read
      actions: read
    needs: [zizmor]
    steps:
      - name: Export workflow
        uses: corentinmusard/otel-cicd-action@f2d88ecf54d9dd3e01ea95e25f93603212ee93d3 # v4
        with:
          otlpEndpoint: ${{ vars.OTEL_EXPORTER_OTLP_ENDPOINT }}/v1/traces
          otlpHeaders: ${{ secrets.OTEL_EXPORTER_HEADERS }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
